---
- name: Pull Docker Image
  community.docker.docker_image:
    name: jellyfin/jellyfin:latest
    source: pull

- name: Start Jelly Container
  community.docker.docker_container:
    name: jellyfin
    image: jellyfin/jellyfin:latest
    network_mode: host
    volumes:
      - "{{ role_path }}/files/config:/config"
      - "{{ local_media_path }}:/media"
    state: started
    restart_policy: always
