---
- name: Deploy Systemd service
  become: true
  ansible.builtin.template:
    src: jellyfin.service.j2
    dest: /etc/systemd/system/jellyfin.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - restart container

- name: Enable and start jellyfin service
  ansible.builtin.systemd:
    name: jellyfin.service
    enabled: true
    state: started
  become: true
