services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    volumes:
      - /home/meow/containers/jellyfin/config:/config
      - /mnt/sara:/media
      - /mnt/media:/media2
    restart: always
